### ISSUE TITLE
Shouldn't keys be able to be not 16 bytes?

### ISSUE THREAD

**Issue by altendky** [kpdemetriou/siphash-cffi#1]
Allows either 4 or 8 bytes:
https://github.com/kpdemetriou/siphash-cffi/blob/d69eae8404eebc5c2c99070d4499cc807672514b/sources/halfsiphash.c#L73-L76

Allows either 8 or 16 bytes:
https://github.com/kpdemetriou/siphash-cffi/blob/d69eae8404eebc5c2c99070d4499cc807672514b/sources/siphash.c#L78-L81

Forces exclusively 16 bytes:
https://github.com/kpdemetriou/siphash-cffi/blob/d69eae8404eebc5c2c99070d4499cc807672514b/siphash/__init__.py#L14-L15

I can work on a PR for this but wanted to confirm I'm not missing something.

**Comment by kpdemetriou** [comment]
Hi @altendky, thanks for pointing this out, you're absolutely right. I will make the appropriate corrections. Unfortunately due to complicated circumstances this will take one to two weeks.

In the meantime, assuming you need this for an active project, I can only suggest monkey-patching `__process_in`. I'll update this issue once the bug has been rectified.

**Comment by altendky** [comment]
I've got a few dependencies where I use forks temporarily so no big deal.  I just try to avoid permanent forks.  If you have some fix other than #2 that's fine of course, or if there are particular concerns with my changes you would like addressed just let me know.

Best of luck with the 'complications'.  No need to rush this for me.

**Comment by altendky** [comment]
@kpdemetriou, I've been pretty busy myself so I understand if you've still got things going.  I just happen to be taking another pass back through this part of our code finally and wanted to check if you had any time to look over this?  It's not blocking me getting anything done, just trying to tidy things up a bit.  :]

**Comment by kpdemetriou** [comment]
Sorry for the long delay; this issue has now been rectified with version 0.1.4. The state of this repository and PyPi have been updated accordingly. Let me know if you run into any more issues.

**Comment by altendky** [comment]
Thanks.  :]
